name: Upload Files to DaRUS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repo to DaRUS 
        uses: IQSS/dataverse-uploader@v1.2
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_API_TOKEN}}
          DATAVERSE_SERVER: https://darus.uni-stuttgart.de
          DATAVERSE_DATASET_DOI: doi:10.18419/darus-2988
          DELETE: False
          PUBLISH: False
