name: Upload Files to DaRUS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repo to DaRUS 
        uses: IQSS/dataverse-uploader@master
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://demo.dataverse.org
          DATAVERSE_DATASET_DOI: doi:10.70122/FK2/JDTKIL
          DELETE: True
          PUBLISH: True
