name: Use "Metadata To Dataverse"-Action and Upload Data to DaRUS

on: [push]

jobs:
  mapper_job:
    runs-on: ubuntu-latest
    name: A job to make a post request to the MetadataMapper
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: MetadataMapper Action Step
        uses: izus-fokus/metadata2dataverse@v0.7
        id: api
        with:
          path: 'codemeta.json'
          dataverse-url: 'https://darus.uni-stuttgart.de'
          doi: '10.18419/darus-3011'
          api-key: '${{ secrets.DATAVERSE_API_TOKEN }}'
      # Use the output from the `MetadataMapper` step
      - name: Get the output
        run: |
          echo ${{ steps.api.outputs.metadata-mapper-result }}
          echo ${{ steps.api.outputs.post-result }}
  upload-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repo to DaRUS 
        uses: IQSS/dataverse-uploader@master
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_API_TOKEN}}
          DATAVERSE_SERVER: https://darus.uni-stuttgart.de
          DATAVERSE_DATASET_DOI: doi:10.18419/darus-3011
          DELETE: True
          PUBLISH: False
